image: alpine:3.4

before_script:
  - apk update && apk add openssl git
  - wget https://github.com/spf13/hugo/releases/download/v0.16/hugo_0.16_linux-64bit.tgz
  - echo "37ee91ab3469afbf7602a091d466dfa5  hugo_0.16_linux-64bit.tgz" | md5sum -c
  - tar xf hugo_0.16_linux-64bit.tgz && cp ./hugo /usr/bin
  - hugo version
  - rm -rf themes
  - mkdir themes
  - git clone https://tgm-git.jade-hs.de/janwillhaus/hugo-tgmsixteen.git themes/tgmsixteen

pages:
  script:
  - hugo
  artifacts:
    paths:
    - public
  only:
  - pages
