layoutdir     = "layouts"
publishdir    = "public"
baseurl       = "http://pub.tgm.io/AES2017NoiseSynthesis"
title         = "Synthesis of Perceptually Plausible Multichannel Noise Signals Controlled by Real World Statistical Noise Properties"
canonifyurls  = true
theme         = "tgmsixteen"

[params]
  subtitle      = "Supplemental Material"
  author        = "Adrian, Gerkmann, van de Par, Bitzer"
