layoutdir     = "layouts"
publishdir    = "public"
baseurl       = "http://pub.tgm.io/AES2016_NoiseSynthesis"
title         = "Test"
canonifyurls  = true
theme         = "tgmsixteen"

[params]
  subtitle      = "Additional Material"
  author        = "Leutz"
